version: '3.8'

services:
  db:
    image: mysql:8.3
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: channel_based_tool_db
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Node.js Backend
  backend:
    build: ./backend
    container_name: node-backend
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: channel_based_tool_db
      DB_PORT: 3306
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: sh -c "npm install && npx sequelize-cli db:create && npx sequelize-cli db:migrate && npm start"

  # React Frontend
  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql-data:
